### ISSUE TITLE
Poyo Sprint 1

### ISSUE THREAD

**Issue by kasistores** [poyo-a-polling-app/poyo-dev#5]
Hello!

We've finished 1/3rd of our user stories please take a look! /cc @codepathreview

**Comment by minhkhang1795** [comment]
I recommend using [Github issue to divide tasks among team members](https://guides.github.com/features/issues/) and easily keep track of the work done.

Anyway, :+1: great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.
